library(dplyr)
MechaCar_mpg <- read.csv(file='MechaCar_mpg.csv',check.names=F,stringsAsFactors = F)
lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD, data=MechaCar_mpg)
summary(lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD, data=MechaCar_mpg)) 
MechaCoil_mpg <- read.csv(file='Suspension_Coil.csv',check.names=F,stringsAsFactors = F)
total_summary <- MechaCoil_mpg %>% summarize(Mean_PSI=mean(PSI),Median_PSI=median(PSI),Var_PSI=var(PSI),Std_Dev_PSI=sd(PSI),Num_Coil=n(), .groups = 'keep') 
lot_summary <- MechaCoil_mpg %>% group_by(Manufacturing_Lot) %>% summarize(Mean_PSI=mean(PSI),Median_PSI=median(PSI),Var_PSI=var(PSI),+Std_Dev_PSI=sd(PSI),+Num_Coil=n(), .groups = 'keep')   
t.test(MechaCoil_mpg$PSI,mu=1500)
lot1 <- subset(MechaCoil_mpg, Manufacturing_Lot=="Lot1")
lot2 <- subset(MechaCoil_mpg, Manufacturing_Lot=="Lot2")
lot3 <- subset(MechaCoil_mpg, Manufacturing_Lot=="Lot3")
t.test(lot1$PSI,mu=1500)
t.test(lot2$PSI,mu=1500)
t.test(lot3$PSI,mu=1500)
